// ─── Devis Templates by Trade ────────────────────────────────────
// 20+ professional templates for French BTP trades

export interface TemplateLineItem {
  designation: string;
  quantity: number;
  unit: string;
  unitPriceHT: number;
  tvaRate: number;
  lineType: string;
  isTitle?: boolean;
}

export interface DevisTemplate {
  id: string;
  name: string;
  description: string;
  trade: string;
  category: string;
  lines: TemplateLineItem[];
}

export const TRADES: Record<string, { label: string; icon: string; color: string }> = {
  plomberie: { label: "Plomberie", icon: "Wrench", color: "#3b82f6" },
  chauffage: { label: "Chauffage", icon: "Flame", color: "#ef4444" },
  electricite: { label: "Électricité", icon: "Zap", color: "#f59e0b" },
  climatisation: { label: "Climatisation", icon: "Wind", color: "#06b6d4" },
  salle_de_bain: { label: "Salle de bain", icon: "Bath", color: "#8b5cf6" },
};

export const DEVIS_TEMPLATES: DevisTemplate[] = [
  // ─── PLOMBERIE ──────────────────────────────────────────
  {
    id: "plb-fuite-robinet",
    name: "Réparation fuite robinet",
    description: "Remplacement de joints et remise en état d'un robinet mitigeur",
    trade: "plomberie",
    category: "Dépannage",
    lines: [
      { designation: "Fournitures", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "fourniture", isTitle: true },
      { designation: "Joint torique robinet mitigeur", quantity: 2, unit: "u", unitPriceHT: 3.50, tvaRate: 10, lineType: "fourniture" },
      { designation: "Cartouche céramique mitigeur", quantity: 1, unit: "u", unitPriceHT: 25.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Téflon + pâte à joint", quantity: 1, unit: "ens", unitPriceHT: 4.50, tvaRate: 10, lineType: "fourniture" },
      { designation: "Main d'œuvre", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "main_oeuvre", isTitle: true },
      { designation: "Déplacement", quantity: 1, unit: "forf", unitPriceHT: 35.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Démontage, remplacement joints et cartouche, remontage", quantity: 1, unit: "h", unitPriceHT: 45.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Essai d'étanchéité et mise en service", quantity: 0.5, unit: "h", unitPriceHT: 45.00, tvaRate: 10, lineType: "main_oeuvre" },
    ],
  },
  {
    id: "plb-chasse-eau",
    name: "Remplacement chasse d'eau",
    description: "Remplacement complet du mécanisme de chasse d'eau WC",
    trade: "plomberie",
    category: "Dépannage",
    lines: [
      { designation: "Fournitures", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "fourniture", isTitle: true },
      { designation: "Mécanisme de chasse complet double commande", quantity: 1, unit: "u", unitPriceHT: 35.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Robinet flotteur", quantity: 1, unit: "u", unitPriceHT: 18.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Joint de cloche", quantity: 1, unit: "u", unitPriceHT: 5.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Main d'œuvre", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "main_oeuvre", isTitle: true },
      { designation: "Déplacement", quantity: 1, unit: "forf", unitPriceHT: 35.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Dépose ancien mécanisme et pose du neuf", quantity: 1.5, unit: "h", unitPriceHT: 45.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Réglage et essais", quantity: 0.5, unit: "h", unitPriceHT: 45.00, tvaRate: 10, lineType: "main_oeuvre" },
    ],
  },
  {
    id: "plb-cumulus",
    name: "Remplacement cumulus 200L",
    description: "Dépose ancien chauffe-eau et pose d'un ballon neuf 200L",
    trade: "plomberie",
    category: "Installation",
    lines: [
      { designation: "Fournitures", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "fourniture", isTitle: true },
      { designation: "Ballon d'eau chaude 200L vertical mural", quantity: 1, unit: "u", unitPriceHT: 450.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Groupe de sécurité", quantity: 1, unit: "u", unitPriceHT: 22.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Raccords flexibles inox", quantity: 2, unit: "u", unitPriceHT: 12.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Siphon + entonnoir évacuation", quantity: 1, unit: "u", unitPriceHT: 15.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Réducteur de pression (si nécessaire)", quantity: 1, unit: "u", unitPriceHT: 35.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Main d'œuvre", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "main_oeuvre", isTitle: true },
      { designation: "Dépose ancien cumulus et évacuation", quantity: 2, unit: "h", unitPriceHT: 45.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Pose nouveau ballon et raccordements", quantity: 3, unit: "h", unitPriceHT: 45.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Mise en service et essais", quantity: 1, unit: "h", unitPriceHT: 45.00, tvaRate: 10, lineType: "main_oeuvre" },
    ],
  },
  {
    id: "plb-debouchage",
    name: "Débouchage canalisation",
    description: "Débouchage canalisation par furet mécanique ou haute pression",
    trade: "plomberie",
    category: "Dépannage",
    lines: [
      { designation: "Diagnostic et intervention", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "main_oeuvre", isTitle: true },
      { designation: "Déplacement et diagnostic", quantity: 1, unit: "forf", unitPriceHT: 45.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Débouchage au furet mécanique", quantity: 1, unit: "forf", unitPriceHT: 120.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Rinçage haute pression de la canalisation", quantity: 1, unit: "forf", unitPriceHT: 80.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Vérification par caméra endoscopique", quantity: 1, unit: "forf", unitPriceHT: 65.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Nettoyage et remise en état des lieux", quantity: 0.5, unit: "h", unitPriceHT: 45.00, tvaRate: 10, lineType: "main_oeuvre" },
    ],
  },
  {
    id: "plb-wc-suspendu",
    name: "Pose WC suspendu",
    description: "Fourniture et pose d'un WC suspendu avec bâti-support",
    trade: "plomberie",
    category: "Installation",
    lines: [
      { designation: "Fournitures", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "fourniture", isTitle: true },
      { designation: "Pack WC suspendu (cuvette + abattant)", quantity: 1, unit: "u", unitPriceHT: 280.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Bâti-support autoportant", quantity: 1, unit: "u", unitPriceHT: 220.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Plaque de commande double touche", quantity: 1, unit: "u", unitPriceHT: 65.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Pipe de raccordement WC", quantity: 1, unit: "u", unitPriceHT: 15.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Raccordements cuivre/PER", quantity: 1, unit: "ens", unitPriceHT: 25.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Main d'œuvre", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "main_oeuvre", isTitle: true },
      { designation: "Dépose ancien WC et évacuation", quantity: 1.5, unit: "h", unitPriceHT: 45.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Pose bâti-support et raccordement", quantity: 3, unit: "h", unitPriceHT: 45.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Habillage bâti (placo + carrelage non inclus)", quantity: 2, unit: "h", unitPriceHT: 45.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Pose cuvette, réglages et mise en service", quantity: 1.5, unit: "h", unitPriceHT: 45.00, tvaRate: 10, lineType: "main_oeuvre" },
    ],
  },
  {
    id: "plb-colonne-eau",
    name: "Remplacement colonne d'eau",
    description: "Remplacement d'une colonne montante eau froide en cuivre",
    trade: "plomberie",
    category: "Rénovation",
    lines: [
      { designation: "Fournitures", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "fourniture", isTitle: true },
      { designation: "Tube cuivre Ø22 (colonne montante)", quantity: 6, unit: "ml", unitPriceHT: 18.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Raccords cuivre (coudes, tés, manchons)", quantity: 1, unit: "ens", unitPriceHT: 45.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Colliers isophoniques fixation", quantity: 6, unit: "u", unitPriceHT: 4.50, tvaRate: 10, lineType: "fourniture" },
      { designation: "Vanne d'arrêt 1/4 de tour", quantity: 2, unit: "u", unitPriceHT: 18.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Main d'œuvre", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "main_oeuvre", isTitle: true },
      { designation: "Purge et dépose ancienne colonne", quantity: 3, unit: "h", unitPriceHT: 45.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Pose nouvelle colonne cuivre brasée", quantity: 5, unit: "h", unitPriceHT: 45.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Raccordement aux piquages existants", quantity: 2, unit: "h", unitPriceHT: 45.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Épreuve pression et mise en service", quantity: 1, unit: "h", unitPriceHT: 45.00, tvaRate: 10, lineType: "main_oeuvre" },
    ],
  },

  // ─── CHAUFFAGE ──────────────────────────────────────────
  {
    id: "chauf-chaudiere-gaz",
    name: "Installation chaudière gaz condensation",
    description: "Fourniture et pose d'une chaudière gaz murale à condensation",
    trade: "chauffage",
    category: "Installation",
    lines: [
      { designation: "Fournitures", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 5.5, lineType: "fourniture", isTitle: true },
      { designation: "Chaudière gaz murale condensation 25kW", quantity: 1, unit: "u", unitPriceHT: 2800.00, tvaRate: 5.5, lineType: "fourniture" },
      { designation: "Kit ventouse horizontale Ø80/125", quantity: 1, unit: "u", unitPriceHT: 120.00, tvaRate: 5.5, lineType: "fourniture" },
      { designation: "Thermostat d'ambiance programmable", quantity: 1, unit: "u", unitPriceHT: 85.00, tvaRate: 5.5, lineType: "fourniture" },
      { designation: "Raccords gaz et kit de raccordement", quantity: 1, unit: "ens", unitPriceHT: 65.00, tvaRate: 5.5, lineType: "fourniture" },
      { designation: "Neutraliseur de condensats", quantity: 1, unit: "u", unitPriceHT: 55.00, tvaRate: 5.5, lineType: "fourniture" },
      { designation: "Main d'œuvre", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 5.5, lineType: "main_oeuvre", isTitle: true },
      { designation: "Dépose ancienne chaudière et évacuation", quantity: 3, unit: "h", unitPriceHT: 50.00, tvaRate: 5.5, lineType: "main_oeuvre" },
      { designation: "Pose chaudière et raccordement hydraulique", quantity: 4, unit: "h", unitPriceHT: 50.00, tvaRate: 5.5, lineType: "main_oeuvre" },
      { designation: "Raccordement gaz et ventouse", quantity: 2, unit: "h", unitPriceHT: 50.00, tvaRate: 5.5, lineType: "main_oeuvre" },
      { designation: "Mise en service et réglages", quantity: 2, unit: "h", unitPriceHT: 50.00, tvaRate: 5.5, lineType: "main_oeuvre" },
      { designation: "Certificat de conformité gaz", quantity: 1, unit: "forf", unitPriceHT: 120.00, tvaRate: 5.5, lineType: "main_oeuvre" },
    ],
  },
  {
    id: "chauf-radiateur",
    name: "Pose radiateur acier",
    description: "Fourniture et pose d'un radiateur acier sur circuit existant",
    trade: "chauffage",
    category: "Installation",
    lines: [
      { designation: "Fournitures", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "fourniture", isTitle: true },
      { designation: "Radiateur acier type 22 — 1000x600mm", quantity: 1, unit: "u", unitPriceHT: 180.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Robinet thermostatique", quantity: 1, unit: "u", unitPriceHT: 28.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Coude de réglage (retour)", quantity: 1, unit: "u", unitPriceHT: 15.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Kit de raccordement + purgeur + bouchon", quantity: 1, unit: "ens", unitPriceHT: 12.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Consoles murales fixation", quantity: 2, unit: "u", unitPriceHT: 8.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Main d'œuvre", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "main_oeuvre", isTitle: true },
      { designation: "Dépose ancien radiateur (si applicable)", quantity: 1, unit: "h", unitPriceHT: 45.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Pose consoles et radiateur", quantity: 1.5, unit: "h", unitPriceHT: 45.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Raccordement circuit et purge", quantity: 1, unit: "h", unitPriceHT: 45.00, tvaRate: 10, lineType: "main_oeuvre" },
    ],
  },
  {
    id: "chauf-plancher",
    name: "Plancher chauffant (pièce 20m²)",
    description: "Fourniture et pose d'un plancher chauffant eau chaude pour une pièce de 20m²",
    trade: "chauffage",
    category: "Installation",
    lines: [
      { designation: "Fournitures", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 5.5, lineType: "fourniture", isTitle: true },
      { designation: "Tube PER Ø16 pour plancher chauffant", quantity: 80, unit: "ml", unitPriceHT: 2.80, tvaRate: 5.5, lineType: "fourniture" },
      { designation: "Panneau isolant à plots (R=1.5)", quantity: 20, unit: "m²", unitPriceHT: 22.00, tvaRate: 5.5, lineType: "fourniture" },
      { designation: "Collecteur inox 2 circuits", quantity: 1, unit: "u", unitPriceHT: 145.00, tvaRate: 5.5, lineType: "fourniture" },
      { designation: "Bande périphérique", quantity: 18, unit: "ml", unitPriceHT: 2.50, tvaRate: 5.5, lineType: "fourniture" },
      { designation: "Additif chape fluide", quantity: 1, unit: "ens", unitPriceHT: 45.00, tvaRate: 5.5, lineType: "fourniture" },
      { designation: "Main d'œuvre", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 5.5, lineType: "main_oeuvre", isTitle: true },
      { designation: "Préparation du sol et pose isolant", quantity: 4, unit: "h", unitPriceHT: 50.00, tvaRate: 5.5, lineType: "main_oeuvre" },
      { designation: "Pose tubes PER en escargot", quantity: 6, unit: "h", unitPriceHT: 50.00, tvaRate: 5.5, lineType: "main_oeuvre" },
      { designation: "Raccordement collecteur", quantity: 2, unit: "h", unitPriceHT: 50.00, tvaRate: 5.5, lineType: "main_oeuvre" },
      { designation: "Épreuve pression et mise en eau", quantity: 1.5, unit: "h", unitPriceHT: 50.00, tvaRate: 5.5, lineType: "main_oeuvre" },
    ],
  },
  {
    id: "chauf-entretien-chaudiere",
    name: "Entretien annuel chaudière gaz",
    description: "Révision annuelle obligatoire chaudière gaz avec attestation",
    trade: "chauffage",
    category: "Entretien",
    lines: [
      { designation: "Entretien annuel", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "main_oeuvre", isTitle: true },
      { designation: "Déplacement technicien", quantity: 1, unit: "forf", unitPriceHT: 30.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Nettoyage brûleur et échangeur", quantity: 1, unit: "forf", unitPriceHT: 45.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Contrôle étanchéité circuit gaz", quantity: 1, unit: "forf", unitPriceHT: 25.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Analyse de combustion", quantity: 1, unit: "forf", unitPriceHT: 20.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Vérification organes de sécurité", quantity: 1, unit: "forf", unitPriceHT: 15.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Attestation d'entretien annuel", quantity: 1, unit: "forf", unitPriceHT: 15.00, tvaRate: 10, lineType: "main_oeuvre" },
    ],
  },
  {
    id: "chauf-pompe-chaleur",
    name: "Installation pompe à chaleur air/eau",
    description: "Fourniture et pose d'une PAC air/eau monobloc extérieure",
    trade: "chauffage",
    category: "Installation",
    lines: [
      { designation: "Fournitures", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 5.5, lineType: "fourniture", isTitle: true },
      { designation: "Pompe à chaleur air/eau monobloc 8kW", quantity: 1, unit: "u", unitPriceHT: 5500.00, tvaRate: 5.5, lineType: "fourniture" },
      { designation: "Ballon tampon 100L", quantity: 1, unit: "u", unitPriceHT: 450.00, tvaRate: 5.5, lineType: "fourniture" },
      { designation: "Kit hydraulique (circulateur, vanne 3 voies)", quantity: 1, unit: "ens", unitPriceHT: 380.00, tvaRate: 5.5, lineType: "fourniture" },
      { designation: "Liaison frigorifique (si split)", quantity: 6, unit: "ml", unitPriceHT: 45.00, tvaRate: 5.5, lineType: "fourniture" },
      { designation: "Support anti-vibratile", quantity: 1, unit: "u", unitPriceHT: 75.00, tvaRate: 5.5, lineType: "fourniture" },
      { designation: "Main d'œuvre", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 5.5, lineType: "main_oeuvre", isTitle: true },
      { designation: "Dalle béton extérieure + pose unité", quantity: 4, unit: "h", unitPriceHT: 55.00, tvaRate: 5.5, lineType: "main_oeuvre" },
      { designation: "Raccordement hydraulique intérieur", quantity: 6, unit: "h", unitPriceHT: 55.00, tvaRate: 5.5, lineType: "main_oeuvre" },
      { designation: "Raccordement électrique (hors tableau)", quantity: 3, unit: "h", unitPriceHT: 55.00, tvaRate: 5.5, lineType: "main_oeuvre" },
      { designation: "Mise en service et paramétrage", quantity: 3, unit: "h", unitPriceHT: 55.00, tvaRate: 5.5, lineType: "main_oeuvre" },
    ],
  },

  // ─── ELECTRICITE ────────────────────────────────────────
  {
    id: "elec-tableau",
    name: "Mise aux normes tableau électrique",
    description: "Remplacement du tableau électrique avec mise en conformité NF C 15-100",
    trade: "electricite",
    category: "Rénovation",
    lines: [
      { designation: "Fournitures", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "fourniture", isTitle: true },
      { designation: "Coffret 3 rangées 39 modules", quantity: 1, unit: "u", unitPriceHT: 85.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Interrupteur différentiel 40A type AC", quantity: 2, unit: "u", unitPriceHT: 42.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Interrupteur différentiel 40A type A", quantity: 1, unit: "u", unitPriceHT: 55.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Disjoncteur 10A (éclairage)", quantity: 4, unit: "u", unitPriceHT: 8.50, tvaRate: 10, lineType: "fourniture" },
      { designation: "Disjoncteur 16A (prises)", quantity: 6, unit: "u", unitPriceHT: 8.50, tvaRate: 10, lineType: "fourniture" },
      { designation: "Disjoncteur 20A (spécialisés)", quantity: 3, unit: "u", unitPriceHT: 9.50, tvaRate: 10, lineType: "fourniture" },
      { designation: "Disjoncteur 32A (plaque cuisson)", quantity: 1, unit: "u", unitPriceHT: 14.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Peigne de raccordement horizontal", quantity: 2, unit: "u", unitPriceHT: 18.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Bornier de terre + câble 6mm²", quantity: 1, unit: "ens", unitPriceHT: 22.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Main d'œuvre", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "main_oeuvre", isTitle: true },
      { designation: "Dépose ancien tableau", quantity: 2, unit: "h", unitPriceHT: 50.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Câblage et raccordement nouveau tableau", quantity: 5, unit: "h", unitPriceHT: 50.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Vérification des circuits et mise sous tension", quantity: 2, unit: "h", unitPriceHT: 50.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Attestation de conformité Consuel", quantity: 1, unit: "forf", unitPriceHT: 150.00, tvaRate: 10, lineType: "main_oeuvre" },
    ],
  },
  {
    id: "elec-prises-piece",
    name: "Ajout prises dans une pièce",
    description: "Pose de 4 prises de courant et 2 points lumineux dans une pièce",
    trade: "electricite",
    category: "Installation",
    lines: [
      { designation: "Fournitures", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "fourniture", isTitle: true },
      { designation: "Prise 2P+T encastrée", quantity: 4, unit: "u", unitPriceHT: 8.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Interrupteur va-et-vient", quantity: 2, unit: "u", unitPriceHT: 9.50, tvaRate: 10, lineType: "fourniture" },
      { designation: "Boîte d'encastrement Ø67", quantity: 6, unit: "u", unitPriceHT: 1.20, tvaRate: 10, lineType: "fourniture" },
      { designation: "Câble R2V 3G2.5 (prises)", quantity: 20, unit: "ml", unitPriceHT: 2.80, tvaRate: 10, lineType: "fourniture" },
      { designation: "Câble R2V 3G1.5 (éclairage)", quantity: 15, unit: "ml", unitPriceHT: 2.20, tvaRate: 10, lineType: "fourniture" },
      { designation: "Gaine ICTA Ø20", quantity: 25, unit: "ml", unitPriceHT: 1.50, tvaRate: 10, lineType: "fourniture" },
      { designation: "Main d'œuvre", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "main_oeuvre", isTitle: true },
      { designation: "Saignées et percements", quantity: 3, unit: "h", unitPriceHT: 50.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Tirage câbles et pose appareillage", quantity: 4, unit: "h", unitPriceHT: 50.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Raccordement au tableau", quantity: 1, unit: "h", unitPriceHT: 50.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Rebouchage saignées (hors finition peinture)", quantity: 1, unit: "h", unitPriceHT: 45.00, tvaRate: 10, lineType: "main_oeuvre" },
    ],
  },
  {
    id: "elec-spot-led",
    name: "Pose spots LED encastrés",
    description: "Fourniture et pose de 6 spots LED encastrés dans faux plafond",
    trade: "electricite",
    category: "Installation",
    lines: [
      { designation: "Fournitures", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "fourniture", isTitle: true },
      { designation: "Spot LED encastré 7W blanc chaud IP44", quantity: 6, unit: "u", unitPriceHT: 18.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Transformateur LED 12V 60W", quantity: 1, unit: "u", unitPriceHT: 35.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Câble H07V-U 1.5mm²", quantity: 15, unit: "ml", unitPriceHT: 1.20, tvaRate: 10, lineType: "fourniture" },
      { designation: "Dominos et connecteurs Wago", quantity: 1, unit: "ens", unitPriceHT: 8.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Main d'œuvre", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "main_oeuvre", isTitle: true },
      { designation: "Perçage faux plafond et pose spots", quantity: 2, unit: "h", unitPriceHT: 50.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Câblage et raccordement", quantity: 2, unit: "h", unitPriceHT: 50.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Essais et réglages", quantity: 0.5, unit: "h", unitPriceHT: 50.00, tvaRate: 10, lineType: "main_oeuvre" },
    ],
  },
  {
    id: "elec-volet-roulant",
    name: "Installation volet roulant électrique",
    description: "Fourniture et pose d'un volet roulant motorisé avec commande murale",
    trade: "electricite",
    category: "Installation",
    lines: [
      { designation: "Fournitures", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "fourniture", isTitle: true },
      { designation: "Volet roulant alu motorisé (L 1400 x H 1200)", quantity: 1, unit: "u", unitPriceHT: 350.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Commande murale filaire", quantity: 1, unit: "u", unitPriceHT: 22.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Câble 4G0.75 (alimentation moteur)", quantity: 8, unit: "ml", unitPriceHT: 2.50, tvaRate: 10, lineType: "fourniture" },
      { designation: "Disjoncteur 10A dédié", quantity: 1, unit: "u", unitPriceHT: 8.50, tvaRate: 10, lineType: "fourniture" },
      { designation: "Main d'œuvre", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "main_oeuvre", isTitle: true },
      { designation: "Dépose ancien volet (si existant)", quantity: 1, unit: "h", unitPriceHT: 45.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Pose caisson et volet roulant", quantity: 2, unit: "h", unitPriceHT: 50.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Tirage câble et raccordement électrique", quantity: 1.5, unit: "h", unitPriceHT: 50.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Réglage fins de course et essais", quantity: 0.5, unit: "h", unitPriceHT: 50.00, tvaRate: 10, lineType: "main_oeuvre" },
    ],
  },

  // ─── CLIMATISATION ──────────────────────────────────────
  {
    id: "clim-split-mono",
    name: "Installation clim split mono",
    description: "Fourniture et pose d'un climatiseur split mural réversible",
    trade: "climatisation",
    category: "Installation",
    lines: [
      { designation: "Fournitures", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 20, lineType: "fourniture", isTitle: true },
      { designation: "Climatiseur split mural réversible 2.5kW", quantity: 1, unit: "u", unitPriceHT: 850.00, tvaRate: 20, lineType: "fourniture" },
      { designation: "Liaison frigorifique 1/4 - 3/8 pré-dudgeonnée", quantity: 4, unit: "ml", unitPriceHT: 35.00, tvaRate: 20, lineType: "fourniture" },
      { designation: "Goulotte PVC de couverture", quantity: 3, unit: "ml", unitPriceHT: 12.00, tvaRate: 20, lineType: "fourniture" },
      { designation: "Support mural unité extérieure", quantity: 1, unit: "u", unitPriceHT: 45.00, tvaRate: 20, lineType: "fourniture" },
      { designation: "Câble d'alimentation 3G2.5", quantity: 8, unit: "ml", unitPriceHT: 3.50, tvaRate: 20, lineType: "fourniture" },
      { designation: "Main d'œuvre", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 20, lineType: "main_oeuvre", isTitle: true },
      { designation: "Percement mur et passage de liaison", quantity: 1.5, unit: "h", unitPriceHT: 55.00, tvaRate: 20, lineType: "main_oeuvre" },
      { designation: "Pose unité intérieure et extérieure", quantity: 2, unit: "h", unitPriceHT: 55.00, tvaRate: 20, lineType: "main_oeuvre" },
      { designation: "Raccordement frigorifique et électrique", quantity: 2, unit: "h", unitPriceHT: 55.00, tvaRate: 20, lineType: "main_oeuvre" },
      { designation: "Tirage au vide et charge fluide", quantity: 1, unit: "h", unitPriceHT: 55.00, tvaRate: 20, lineType: "main_oeuvre" },
      { designation: "Mise en service et essais", quantity: 1, unit: "h", unitPriceHT: 55.00, tvaRate: 20, lineType: "main_oeuvre" },
    ],
  },
  {
    id: "clim-multi-split",
    name: "Installation clim multi-split (3 pièces)",
    description: "Fourniture et pose d'un système multi-split 3 unités murales",
    trade: "climatisation",
    category: "Installation",
    lines: [
      { designation: "Fournitures", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 20, lineType: "fourniture", isTitle: true },
      { designation: "Groupe extérieur multi-split 3 sorties 6.8kW", quantity: 1, unit: "u", unitPriceHT: 2200.00, tvaRate: 20, lineType: "fourniture" },
      { designation: "Unité murale intérieure 2.5kW", quantity: 2, unit: "u", unitPriceHT: 380.00, tvaRate: 20, lineType: "fourniture" },
      { designation: "Unité murale intérieure 3.5kW", quantity: 1, unit: "u", unitPriceHT: 420.00, tvaRate: 20, lineType: "fourniture" },
      { designation: "Liaison frigorifique 1/4 - 3/8", quantity: 18, unit: "ml", unitPriceHT: 35.00, tvaRate: 20, lineType: "fourniture" },
      { designation: "Goulotte PVC + accessoires", quantity: 12, unit: "ml", unitPriceHT: 12.00, tvaRate: 20, lineType: "fourniture" },
      { designation: "Support sol extérieur anti-vibratile", quantity: 1, unit: "u", unitPriceHT: 65.00, tvaRate: 20, lineType: "fourniture" },
      { designation: "Main d'œuvre", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 20, lineType: "main_oeuvre", isTitle: true },
      { designation: "Percements murs (3 passages)", quantity: 3, unit: "h", unitPriceHT: 55.00, tvaRate: 20, lineType: "main_oeuvre" },
      { designation: "Pose 3 unités intérieures", quantity: 4, unit: "h", unitPriceHT: 55.00, tvaRate: 20, lineType: "main_oeuvre" },
      { designation: "Pose unité extérieure", quantity: 1.5, unit: "h", unitPriceHT: 55.00, tvaRate: 20, lineType: "main_oeuvre" },
      { designation: "Raccordements frigorifiques et électriques", quantity: 5, unit: "h", unitPriceHT: 55.00, tvaRate: 20, lineType: "main_oeuvre" },
      { designation: "Tirage au vide, charge fluide et mise en service", quantity: 2, unit: "h", unitPriceHT: 55.00, tvaRate: 20, lineType: "main_oeuvre" },
    ],
  },
  {
    id: "clim-entretien",
    name: "Entretien climatisation split",
    description: "Nettoyage et vérification annuelle d'un climatiseur split",
    trade: "climatisation",
    category: "Entretien",
    lines: [
      { designation: "Entretien annuel", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 20, lineType: "main_oeuvre", isTitle: true },
      { designation: "Déplacement technicien", quantity: 1, unit: "forf", unitPriceHT: 35.00, tvaRate: 20, lineType: "main_oeuvre" },
      { designation: "Nettoyage filtres et unité intérieure", quantity: 1, unit: "forf", unitPriceHT: 35.00, tvaRate: 20, lineType: "main_oeuvre" },
      { designation: "Nettoyage condenseur extérieur", quantity: 1, unit: "forf", unitPriceHT: 30.00, tvaRate: 20, lineType: "main_oeuvre" },
      { designation: "Contrôle pression fluide frigorigène", quantity: 1, unit: "forf", unitPriceHT: 25.00, tvaRate: 20, lineType: "main_oeuvre" },
      { designation: "Vérification électrique et fonctionnelle", quantity: 1, unit: "forf", unitPriceHT: 20.00, tvaRate: 20, lineType: "main_oeuvre" },
      { designation: "Traitement antibactérien évaporateur", quantity: 1, unit: "forf", unitPriceHT: 15.00, tvaRate: 20, lineType: "main_oeuvre" },
    ],
  },

  // ─── SALLE DE BAIN ──────────────────────────────────────
  {
    id: "sdb-renovation-complete",
    name: "Rénovation salle de bain complète",
    description: "Rénovation complète salle de bain 6m² : plomberie, sanitaires, carrelage",
    trade: "salle_de_bain",
    category: "Rénovation",
    lines: [
      { designation: "Dépose existant", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "main_oeuvre", isTitle: true },
      { designation: "Dépose sanitaires existants (baignoire, lavabo, WC)", quantity: 4, unit: "h", unitPriceHT: 45.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Dépose ancien carrelage sol et murs", quantity: 8, unit: "h", unitPriceHT: 45.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Évacuation gravats", quantity: 1, unit: "forf", unitPriceHT: 150.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Plomberie", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "fourniture", isTitle: true },
      { designation: "Receveur de douche extra-plat 80x120", quantity: 1, unit: "u", unitPriceHT: 280.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Colonne de douche thermostatique", quantity: 1, unit: "u", unitPriceHT: 220.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Paroi de douche fixe 80cm verre 8mm", quantity: 1, unit: "u", unitPriceHT: 320.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Meuble vasque 80cm + miroir LED", quantity: 1, unit: "u", unitPriceHT: 450.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "WC suspendu + bâti-support", quantity: 1, unit: "ens", unitPriceHT: 480.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Sèche-serviettes mixte 750W", quantity: 1, unit: "u", unitPriceHT: 180.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Tuyauterie PER + évacuation PVC", quantity: 1, unit: "ens", unitPriceHT: 120.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Revêtements", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "fourniture", isTitle: true },
      { designation: "Carrelage sol antidérapant", quantity: 6, unit: "m²", unitPriceHT: 35.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Faïence murale", quantity: 15, unit: "m²", unitPriceHT: 28.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Colle + joints + étanchéité SPEC", quantity: 1, unit: "ens", unitPriceHT: 95.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Main d'œuvre pose", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "main_oeuvre", isTitle: true },
      { designation: "Plomberie (alimentations + évacuations)", quantity: 8, unit: "h", unitPriceHT: 50.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Étanchéité (SPEC sous carrelage)", quantity: 4, unit: "h", unitPriceHT: 50.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Pose carrelage sol", quantity: 6, unit: "h", unitPriceHT: 50.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Pose faïence murale", quantity: 12, unit: "h", unitPriceHT: 50.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Pose sanitaires et raccordements", quantity: 6, unit: "h", unitPriceHT: 50.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Pose sèche-serviettes", quantity: 2, unit: "h", unitPriceHT: 50.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Joints silicone finition", quantity: 2, unit: "h", unitPriceHT: 45.00, tvaRate: 10, lineType: "main_oeuvre" },
    ],
  },
  {
    id: "sdb-douche-italienne",
    name: "Création douche à l'italienne",
    description: "Création d'une douche à l'italienne avec receveur encastré et paroi fixe",
    trade: "salle_de_bain",
    category: "Installation",
    lines: [
      { designation: "Fournitures", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "fourniture", isTitle: true },
      { designation: "Receveur extra-plat à carreler 90x120", quantity: 1, unit: "u", unitPriceHT: 180.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Caniveau de douche inox 80cm", quantity: 1, unit: "u", unitPriceHT: 120.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Paroi fixe verre 10mm — 120cm", quantity: 1, unit: "u", unitPriceHT: 380.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Colonne de douche encastrée thermostatique", quantity: 1, unit: "u", unitPriceHT: 350.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Kit étanchéité SPEC complet", quantity: 1, unit: "ens", unitPriceHT: 85.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Carrelage sol antidérapant douche", quantity: 2, unit: "m²", unitPriceHT: 45.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Main d'œuvre", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "main_oeuvre", isTitle: true },
      { designation: "Dépose existant (si remplacement baignoire)", quantity: 4, unit: "h", unitPriceHT: 45.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Création de forme de pente", quantity: 3, unit: "h", unitPriceHT: 50.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Pose receveur et caniveau", quantity: 3, unit: "h", unitPriceHT: 50.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Étanchéité complète (sol + remontées mur)", quantity: 4, unit: "h", unitPriceHT: 50.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Pose carrelage sol douche", quantity: 3, unit: "h", unitPriceHT: 50.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Plomberie (alimentation + évacuation)", quantity: 4, unit: "h", unitPriceHT: 50.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Pose paroi vitrée", quantity: 2, unit: "h", unitPriceHT: 50.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Joints silicone et finitions", quantity: 1.5, unit: "h", unitPriceHT: 45.00, tvaRate: 10, lineType: "main_oeuvre" },
    ],
  },
  {
    id: "sdb-remplacement-baignoire",
    name: "Remplacement baignoire par douche",
    description: "Dépose baignoire et installation d'une douche avec bac et paroi",
    trade: "salle_de_bain",
    category: "Rénovation",
    lines: [
      { designation: "Dépose", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "main_oeuvre", isTitle: true },
      { designation: "Dépose baignoire + tablier + robinetterie", quantity: 3, unit: "h", unitPriceHT: 45.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Évacuation baignoire et gravats", quantity: 1, unit: "forf", unitPriceHT: 80.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Fournitures sanitaires", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "fourniture", isTitle: true },
      { designation: "Receveur de douche céramique 80x120", quantity: 1, unit: "u", unitPriceHT: 250.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Paroi de douche pivotante 80cm", quantity: 1, unit: "u", unitPriceHT: 280.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Mitigeur thermostatique mural", quantity: 1, unit: "u", unitPriceHT: 150.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Douchette + flexible + barre de douche", quantity: 1, unit: "ens", unitPriceHT: 65.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Bonde de douche Ø60", quantity: 1, unit: "u", unitPriceHT: 25.00, tvaRate: 10, lineType: "fourniture" },
      { designation: "Adaptation plomberie", quantity: 1, unit: "u", unitPriceHT: 0, tvaRate: 10, lineType: "main_oeuvre", isTitle: true },
      { designation: "Modification alimentation (repositionnement)", quantity: 3, unit: "h", unitPriceHT: 50.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Modification évacuation", quantity: 2, unit: "h", unitPriceHT: 50.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Pose receveur et étanchéité", quantity: 3, unit: "h", unitPriceHT: 50.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Pose robinetterie et paroi", quantity: 2, unit: "h", unitPriceHT: 50.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Habillage mur (faïence sur 1m²)", quantity: 3, unit: "h", unitPriceHT: 50.00, tvaRate: 10, lineType: "main_oeuvre" },
      { designation: "Joints silicone et mise en service", quantity: 1, unit: "h", unitPriceHT: 45.00, tvaRate: 10, lineType: "main_oeuvre" },
    ],
  },
];

// ─── Helpers ──────────────────────────────────────────────
export function getTemplatesByTrade(trade?: string): DevisTemplate[] {
  if (!trade) return DEVIS_TEMPLATES;
  return DEVIS_TEMPLATES.filter(t => t.trade === trade);
}

export function getTemplateById(id: string): DevisTemplate | undefined {
  return DEVIS_TEMPLATES.find(t => t.id === id);
}
